name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [1.8, 11, 15]
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew build publishToMavenLocal --parallel --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
