name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 15-jdk]
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: openjdk:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publishToMavenLocal --parallel --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
